### ISSUE TITLE
Tapping on a notification causes the game to close and reopen

### ISSUE THREAD

**Issue by bruce-hill** [cengiz-pz/godot-android-notification-scheduler-plugin#3]
When I schedule a notification, I'd really like to have the app simply regain focus instead of quitting the app and launching a new copy of the app (which is the current behavior). I believe the current behavior is caused by this line in `NotificationReceiver.java` which is requesting that the current task is cleared out and a new task is created.

```
notificationActionIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
```

My ultimate goal is to use the deeplink URI with the [Deeplink Plugin](https://github.com/cengiz-pz/godot-android-deeplink-plugin) to be able to trigger notifications that send me to a specific place within my app, ideally without closing and relaunching the app, which is very slow on older devices.

PS- Thanks for this plugin, it's been very helpful! 😃

**Comment by cengiz-pz** [comment]
Hi @bruce-hill, could you please check if your issue is resolved with the latest release?

**Comment by bruce-hill** [comment]
Yes! The new release resolves my issue and it works great! Thanks for your work! If you have a tip jar set up somewhere, I'd be happy to kick in a little 😃
