### ISSUE TITLE
Minor README question

### ISSUE THREAD

**Issue by zaddok** [cengiz-pz/godot-android-notification-scheduler-plugin#5]
The readme says to create a channel like this:

    $NotificationScheduler.create_notification_channel("my_channel_id", "My Channel Name", "My channel description")

But it looks like its changed so that an object is needed like this, is that correct?

	var channel = NotificationChannel.new()
	channel.set_id("hello")
	channel.set_name("Reminders")
	channel.set_description("Reminders")
	self.notifications.create_notification_channel(channel)

**Comment by cengiz-pz** [comment]
Hi @zaddok.  Yes, you're right; it looks like the README needs to be updated.  Thanks for the heads up.  Yes, you're right; it looks like the README needs to be updated.
