### ISSUE TITLE
Adjust Channel Importance

### ISSUE THREAD

**Issue by zaddok** [cengiz-pz/godot-android-notification-scheduler-plugin#6]
Thank you for sharing this, much appreciated.

When my local notifications are sent, I am not seeing a popup slide in on to the screen in the same way I see it on iOS. I think I am trying to make the "Settings -> notifications -> app name -> Pop On Screen" set to on by default. (If this is possible) I am trying to work out why it is not on. It may be related to when a channel is created. 

There appear to be multiple options, ie:

https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_DEFAULT

And it seems like `IMPORTANCE_HIGH` _might_ be needed in order to make a popup appear on screen. But the `NotficationChannel` Godot class does not appear to have a way to set channel importance, is that correct? How do we set channel importance? Will a patch to the android plugin be needed?

**Comment by zaddok** [comment]
I've done some testing, IMPORTANCE_HIGH does allow on screen notifications. Each of these settings have numbers in the documentation, ie:

IMPORTANCE_HIGH = 4,
IMPORTANCE_DEFAULT = 3,
IMPORTANCE_LOW = 2,

So perhaps we need to be able to pass in an int or an enum.

**Comment by zaddok** [comment]
Im trying to work out how to build the plugin from source by opening it with Android Studio but there are all sorts of build errors I don't know anything about. Im not sure how long it's going to take. :). 

Is there any chance you could push out an update for us that allows changing the channel importance. In the mean time I'll keep googling weird grade errors. :)

**Comment by cengiz-pz** [comment]
Hi @zaddok, this seems to be a good feature to add to the plugin.  Thanks for bringing it up.  I'll look into it when I get the chance.

**Comment by cengiz-pz** [comment]
Hi @zaddok, let me know if the new release resolves this issue.

https://github.com/cengiz-pz/godot-android-notification-scheduler-plugin/releases/tag/v2.1
